services:
  gfp-db:
    container_name: gfp-db
    image: postgres:16.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-password}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT-5432}:${DB_PORT-5432}
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/dev/server.dockerfile
    restart: unless-stopped
    ports:
      - ${PORT-3000}:${PORT-3000}
    develop:
      watch:
        # - action: sync
        #   path: ./server
        #   target: /app
        - action: rebuild
          path: ./server
    depends_on:
      - gfp-db
    environment:
      - HOST=${HOST-localhost}
      - PORT=${PORT-3000}
      - MODE=${MODE-dev}
      # - DATABASE_URL=postgresql://postgres:${DB_PASS-password}@db:${DB_PORT-5432}/postgres
      - DB_HOST=gfp-db
      - DB_PORT=${DB_PORT-5432}
      - DB_PASS=${DB_PASS-password}
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=${DB_SSLMODE-disable}
